---
stages:
  - test
  - build
  - post-test
  - deploy

include:
  - component: $CI_SERVER_FQDN/ci/security/bundle@1
  - component: $CI_SERVER_FQDN/ci/typescript/lint-check@2
  - component: $CI_SERVER_FQDN/ci/typescript/build@2
  - component: $CI_SERVER_FQDN/ci/docker/build-and-scan@4
    inputs:
      name: frontend
      image: frontend
      tags: latest,$CI_COMMIT_SHA
      build_args: --secret id=SENTRY_AUTH_TOKEN,type=env
      rules_changes:
        - "**/*"
  - component: $CI_SERVER_FQDN/ci/helmfile/deploy@2
    inputs:
      working_dir: support/kubernetes
      helmfile_path: support/kubernetes/helmfile.yaml.gotmpl

helmfile deploy:
  environment:
    name: production
    url: https://vapronva.pw
