pipeline:
  update-docker-compose:
    image: devforth/drone-builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - /bin/bash build.sh
    when:
      branch: main
