version: "3"

services:
  vapronvapwwebsite:
    image: registry.vapronva.pw/websites/vapronva_pw-website:latest
    container_name: "web-vapronvapw"
    environment:
      - VIRTUAL_HOST=vapronva.pw
      - VIRTUAL_PORT=8000
    networks:
      - "w-vapronvapw-network"

networks:
  w-vapronvapw-network:
    external: true
