---
nameOverride: frontend-vapronvapw
fullnameOverride: frontend-vapronvapw-vprw

deployment:
  containers:
    - name: frontend
      image:
        registry: docker.horse
        repository: vapronva/vapronva-pw/frontend
        tag: latest
      ports:
        - name: http
          containerPort: 3000
          protocol: TCP
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - unnecessary-addition

services:
  - name: frontend-vapronvapw
    type: ClusterIP
    ports:
      - name: http
        port: 3000
        targetPort: http
        protocol: TCP

ckic:
  enabled: true
  sites:
    - hosts:
        - vapronva.pw
      upstream: frontend-vapronvapw:3000
