depends_on:
  - "test"

pipeline:
  build-image:
    secrets:
      - "DOCKER_PASSWORD"
      - "DOCKER_USERNAME"
    image: plugins/docker
    settings:
      registry: registry.vapronva.pw
      username: ${DOCKER_USERNAME}
      password: ${DOCKER_PASSWORD}
      dockerfile: ./Dockerfile
      tags:
        - "latest"
    when:
      event: [push]
      path:
        - "vapronvapw/**"
        - ".woodpecker/*.yml"
        - "**/Dockerfile"
