depends_on:
  - "test"
  - "build"

pipeline:
  publish-docker-compose:
    image: devforth/drone-builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - "DOCKER_PASSWORD"
      - "DOCKER_USERNAME"
    commands:
      - "sh publish-dc.sh"
    when:
      branch: main
      event: [push]
      path:
        - "**/*.html"
        - ".woodpecker/*.yml"
        - "**/Dockerfile"
        - "**/docker-compose.yml"
        - "**/*.sh"
